parameters:
     expanded_otm.form: abdielcs\ExpandedCollectionBundle\Form\Type\ExpandedOTMType
     expanded_mtm.form: abdielcs\ExpandedCollectionBundle\Form\Type\ExpandedMTMType

services:
    expanded_otm.service:
       class: "%expanded_otm.form%"
       tags:
          - { name: form.type, alias: 'expanded_otm' }

    expanded_mtm.service:
       class: "%expanded_mtm.form%"
       tags:
          - { name: form.type, alias: 'expanded_mtm' }
